# Site settings
course_name: Internet Video Streaming (ELEC 6910I)
course_description: "Foggy University is the pronunciation of HKUST in Cantonese. Walking in the fog was also my feeling when I was learning computer networks."
course_semester: "Spring 2025"

baseurl: "/spring2025pg/" # the subpath of your site, e.g. /blog/
url: "https://hkust-network.github.io/" # the base hostname & protocol for your site

schoolname: "HKUST ECE"
schoolurl: "https://www.foggynetwork.com"
# twitter_username: username 

address: |
    Department of Electronic and Computer Engineering
    Hong Kong University of Science and Technology
    Hong Kong
    
timezone: Asia/Hong_Kong
# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    tutorials:
        output: true
    assignments:
        output: true
    announcements:
        output: true
    checkpoints:
        output: true


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  - scope:
      path: ""
      type: "checkpoints"
    values:
      layout: "checkpoint"
